# Generated by Django 3.0.2 on 2020-02-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200219_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
