# Generated by Django 3.0.2 on 2020-02-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_department_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.Position'),
        ),
    ]
