# Generated by Django 2.1.1 on 2020-03-24 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_auto_20200323_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.PositiveIntegerField()),
                ('parent_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employee.Department')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='employee.Position'),
        ),
    ]
