# Generated by Django 2.1.1 on 2020-03-24 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_auto_20200324_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentchild',
            name='parent_department',
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='employee.Position'),
        ),
        migrations.DeleteModel(
            name='DepartmentChild',
        ),
    ]
