# Generated by Django 2.1.1 on 2020-03-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='document',
        ),
        migrations.RemoveField(
            model_name='defaulsignlist',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='defaulsignlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='push',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='document',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='DefaulSignList',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Push',
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
