# Generated by Django 3.0.2 on 2020-01-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0002_attachment_document_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
