# Generated by Django 3.0.2 on 2020-01-30 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ea', '0003_auto_20200130_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sign', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
