# Generated by Django 2.1.1 on 2020-03-27 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ea.Invoice'),
            preserve_default=False,
        ),
    ]
