# Generated by Django 3.0.2 on 2020-02-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0005_auto_20200130_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
