# Generated by Django 2.1.1 on 2020-03-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0006_auto_20200327_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='ea.Document'),
            preserve_default=False,
        ),
    ]
