# Generated by Django 3.0.2 on 2020-02-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0007_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='isImg',
            field=models.BooleanField(default=True),
        ),
    ]
