# Generated by Django 2.1.1 on 2020-03-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0008_auto_20200330_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('IDS', models.CharField(max_length=100)),
                ('RPSEQ', models.CharField(max_length=10)),
                ('RPJELN', models.CharField(max_length=10)),
                ('RPDOC', models.CharField(max_length=50)),
                ('RPICU', models.CharField(max_length=30)),
                ('RPICUT', models.CharField(max_length=10)),
                ('RPDCT', models.CharField(max_length=10)),
                ('RPCRCD', models.CharField(max_length=10)),
                ('RPTAX', models.CharField(blank=True, max_length=50, null=True)),
                ('RPALPH', models.CharField(blank=True, max_length=255, null=True)),
                ('RPDGJ', models.CharField(max_length=10)),
                ('RPDSVJ', models.CharField(max_length=10)),
                ('RPEXR1', models.CharField(blank=True, max_length=10, null=True)),
                ('RPTXA1', models.CharField(blank=True, max_length=10, null=True)),
                ('RPPO', models.CharField(blank=True, max_length=50, null=True)),
                ('RPCRR', models.CharField(blank=True, max_length=50, null=True)),
                ('RPMCU', models.CharField(max_length=20)),
                ('RPOBJ', models.CharField(max_length=20)),
                ('RPSUB', models.CharField(max_length=20)),
                ('RPASID', models.CharField(blank=True, max_length=255, null=True)),
                ('RPDC', models.CharField(blank=True, max_length=50, null=True)),
                ('RPZ5DEBITAT', models.IntegerField()),
                ('RPZ5CREDITAT', models.IntegerField()),
                ('RPAMT', models.IntegerField()),
                ('RPZ5FDEDIT', models.IntegerField()),
                ('RPZ5FCREDIT', models.IntegerField()),
                ('RPDL02', models.CharField(max_length=255)),
                ('RPSFX', models.CharField(max_length=10)),
                ('RPRMK', models.CharField(blank=True, max_length=500, null=True)),
                ('RPPDCT', models.CharField(blank=True, max_length=20, null=True)),
                ('RPSBLT', models.CharField(blank=True, max_length=255, null=True)),
                ('RPADDN', models.CharField(blank=True, max_length=255, null=True)),
                ('RPPYE', models.CharField(max_length=20)),
                ('RPDL03', models.CharField(max_length=255)),
                ('RPOST', models.CharField(blank=True, max_length=255, null=True)),
                ('RPAN8', models.CharField(blank=True, max_length=20, null=True)),
                ('RPGLC', models.CharField(blank=True, max_length=10, null=True)),
                ('RPTORG', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_subs', to='ea.Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
