# Generated by Django 3.0.2 on 2020-02-28 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20200228_1420'),
        ('ea', '0008_attachment_isimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='user',
        ),
        migrations.AddField(
            model_name='sign',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sign', to='employee.Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='employee.Employee'),
        ),
    ]
