# Generated by Django 2.1.1 on 2020-04-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0009_invoicesub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesub',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPSEQ',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='InvoiceSub',
        ),
    ]
