# Generated by Django 2.1.1 on 2020-04-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0011_auto_20200407_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='RPCODE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
