# Generated by Django 3.0.2 on 2020-03-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0012_defaulsignlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulsignlist',
            name='type',
            field=models.CharField(choices=[('0', '결재'), ('1', '합의'), ('2', '수신및참조')], default='0', max_length=2),
        ),
    ]
