# Generated by Django 3.0.2 on 2020-03-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20200303_1625'),
        ('ea', '0013_defaulsignlist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='employee.Department'),
        ),
    ]
