# Generated by Django 2.1.1 on 2020-04-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0014_invoice_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='RMDOCM',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPAMT',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPCBNK',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPCKAM',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPCRCD',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPCRR',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPDATE01',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPDCTG',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPDL01',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPDOCG',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPDS50',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPDSC1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPEDIT',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPFCAM',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPFUP',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPIBAN',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPKCO',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPMOT',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPOST',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPSDCT',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPSDOC',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPSWFT',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPTNST',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPU',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPUM',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPUPRC',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPVR01',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPZ5FCREDIT',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RPZ5FDEDIT',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='RYCRR',
        ),
        migrations.AddField(
            model_name='invoice',
            name='RPDOCM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='RPLITM',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPADDN',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPAID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPALPH',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPAN8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPASID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPB76ERN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPCKNU',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPCODE',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDC',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDCTM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDICJ',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDIVJ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDKJ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDL02',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDL03',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDL04',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDL05',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDMTJ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPEXA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPEXR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPEXR1',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPEXR1NM',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPGLBA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPGLC',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPICUA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPJELN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPMCU',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPNFVD',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPOBJ',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPPDCT',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPPN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPPO',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPPST',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPPYE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPPYID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPRC5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPRE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPRMK',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPSBL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPSBLT',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPSEQ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPSFX',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPSUB',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPTAX',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPTORG',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPTXA1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPTYIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPVINV',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPVLDT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
