# Generated by Django 3.0.2 on 2020-03-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0014_auto_20200303_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='group',
        ),
    ]
