# Generated by Django 3.0.2 on 2020-03-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0015_remove_document_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulsignlist',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
