# Generated by Django 2.1.1 on 2020-04-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0015_auto_20200429_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='RPDCT',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDGJ',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDICJ',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPDOC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPICU',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPICUT',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
