# Generated by Django 2.1.1 on 2020-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0016_auto_20200429_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='RPDL02',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPSFX',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPZ5CREDITAT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RPZ5DEBITAT',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
