# Generated by Django 3.0.2 on 2020-03-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0016_defaulsignlist_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulsignlist',
            name='order',
        ),
    ]
