# Generated by Django 2.1.1 on 2020-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0017_auto_20200429_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='document_type',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('0', '채무발생'), ('1', '채무정리'), ('2', '채권발생'), ('3', '채권정리'), ('4', '일반전표')], default='0', max_length=2),
        ),
    ]
