# Generated by Django 3.0.2 on 2020-03-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0018_defaulsignlist_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='batch_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
