# Generated by Django 2.1.1 on 2020-05-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0019_auto_20200504_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulsignlist',
            name='document_type',
            field=models.CharField(choices=[('0', '채무발생'), ('1', '채무정리'), ('2', '채권발생'), ('3', '채권정리'), ('4', '일반전표')], default='0', max_length=2),
        ),
    ]
