# Generated by Django 3.0.2 on 2020-03-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0020_auto_20200306_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='ea.Document'),
        ),
    ]
