# Generated by Django 2.1.1 on 2020-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0020_defaulsignlist_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='endpoint',
            field=models.TextField(),
        ),
    ]
