# Generated by Django 3.0.2 on 2020-03-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ea', '0021_auto_20200306_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='isPdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='isImg',
            field=models.BooleanField(default=False),
        ),
    ]
